**Manual implentation of SVD algorithm and comparaison with numpy.linalg.svd function**

In [1]:
#Importation of the necessary libraries
import numpy as np

In [2]:
#Implementation of a basic SVD function, a function that doesn't resolve the problem of null singular values
def basic_SVD(A):
  #Forming the Gram matrix
  S=np.dot(A.T, A)

  #Calculation of eigenvalues and eigenvectors
  eig_val, eig_vec=np.linalg.eig(S)

  #Verification of the presence of null eigenvalue
  if np.min(eig_val)<=0:
    print('error')

  else:
    #Descending sorting of non_null eigeenvalues
    indices=eig_val.argsort()[::-1]
    eig_val_sorted=eig_val[indices]

    #Sorting of corresponding eigenvectors
    eig_vec_sorted=eig_vec[: , indices]

    #Singular values determination
    sigma=np.sqrt(eig_val_sorted)

    #Diagonalisation of singular value matrix
    SIGMA=np.diag(sigma)

    #Composition of right singular vector
    V=eig_vec_sorted

    #Composition of left singualr vector
    U=[]
    for i in range(len(sigma)):
      u=np.dot(A, V[: , i])/sigma[i]
      U.append(u)
    U=np.column_stack(U)

    #Decomposition of the matrix A
    svd=np.dot(np.dot(U, SIGMA), V.T)

    return svd, U, SIGMA, V



In [3]:
#Implementation of SVD function that handles null singular values
def red_SVD(A):

  #Gram matrix construction
  S=np.dot(A.T, A)

  #Calculation of eigenvalues and eigenvectors
  eig_val, eig_vec=np.linalg.eig(S)

  #Zeroing negative (usually very small) eigenvalues
  eig_val[eig_val<0]=0

  #Descending sorting of non_null eigeenvalues
  index=eig_val.argsort()[::-1]
  eig_val_sorted=eig_val[index]

  #Sorting of corresponding eigenvectors
  eig_vec_sorted=eig_vec[: , index]

  #Calculation of sigular values
  sigma=np.sqrt(eig_val_sorted)

  #Creation of non_zero singular values mask (filtering singular values and only preserving non null ones )
  non_zero=sigma>1e-6
  sigma_red=sigma[non_zero]

  #Creation of singular value matrix
  SIGMA_red=np.diag(sigma_red)

  #Creation of "a reduced" right singualr vector
  V_red=eig_vec_sorted[: , non_zero]

  #Creation of "a reduced" left singular vector
  U=[]
  for i in range(len(sigma_red)):
    u=A@V_red[: , i]/sigma_red[i]
    U.append(u)
  U_red=np.column_stack(U)

  #Decomposition of the matrix
  svd=U_red@SIGMA_red@V_red.T
  return svd, U_red, SIGMA_red, V_red.T


In [4]:
#Generation of a random matrix
A=np.random.rand(3 , 3)
print(A)

[[6.80668829e-04 9.09190470e-02 7.13795445e-01]
 [8.96457356e-01 5.26293260e-01 4.36171907e-01]
 [4.13707157e-01 5.38163898e-01 6.75605819e-01]]


In [5]:
#Testing the basic version of SVD fucntion
svd_basic, U_basic, SIGMA_basic, V_basic=basic_SVD(A)
print(svd_basic)

[[6.80668829e-04 9.09190470e-02 7.13795445e-01]
 [8.96457356e-01 5.26293260e-01 4.36171907e-01]
 [4.13707157e-01 5.38163898e-01 6.75605819e-01]]


In [6]:
#Decompostion using numpy library
U, S, Vt=np.linalg.svd(A, full_matrices=False)
SVD_numpy=U @ np.diag(S)@Vt
print(U @ np.diag(S)@Vt)

[[6.80668829e-04 9.09190470e-02 7.13795445e-01]
 [8.96457356e-01 5.26293260e-01 4.36171907e-01]
 [4.13707157e-01 5.38163898e-01 6.75605819e-01]]


In [7]:
#Testing the reduced version of SVD
svd_reduced, U, SIGMA, V=red_SVD(A)
print(svd_reduced)

[[6.80668829e-04 9.09190470e-02 7.13795445e-01]
 [8.96457356e-01 5.26293260e-01 4.36171907e-01]
 [4.13707157e-01 5.38163898e-01 6.75605819e-01]]
